//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EDU2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physician
    {
        public int id { get; set; }
        public string Npi { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Speciality { get; set; }
        public double ConsultationCharges { get; set; }
        public int Hospital { get; set; }
    }
}
